print("Введите число a:")
a = int(input())
print("Введите число b:")
b = int(input())

print("Сумма a и b =", a + b)
print("Разность a и b =", a - b)
print("Произведение a и b =", a * b)
print("Частное от деления a на b =", a / b)
print("Остаток от деления a на b =", a % b)
print("Результат возведения числа a в степень b =", a ** b)